version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      DEBUG: "TRUE"
      ONLINE_MODE: "FALSE"

      SERVER_NAME: "Our Minecraft Server"
      MOTD: "First Peaceful World"

    volumes:
      - ./minecraft-data:/data
